### ISSUE TITLE
is 1.15 missing @common before_install section ?

### ISSUE THREAD

**Issue by gempesaw** [SineSwiper/Dist-Zilla-TravisCI#32]
Hey,

Just upgraded to 1.15 and I'm noticing that haarg's travis-ci perl helpers aren't getting put into the `before_install` section of my `.travis.yml`. Am I doing something wrong ?

dist.ini section:
```ini
[TravisYML]
build_branch = cpan
perl_version = 5.20 5.18 5.16 5.14 5.12 5.10
test_authordeps = 0
test_deps = 0
```

I ran the following bash commands:

```bash
cpanm --reinstall Dist::Zilla::Plugin::TravisYML
dzil new TestThing
cd TestThing/
dzil build
cat .travis.yml
```

and got the following travis yaml file:

```yaml
sudo: false
language: perl
perl:
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
script:
   - dzil smoke --release --author
```

(transcript with bash output: https://gist.github.com/gempesaw/4d7680b2d2a83dd152fb )

thanks! :D
